// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1FDCddk_LbieylOJh4rZQUiI9kNjHjOs',
    appId: '1:266111988879:web:01ed8b485e9a033819acfa',
    messagingSenderId: '266111988879',
    projectId: 'veamordatingapp',
    authDomain: 'veamordatingapp.firebaseapp.com',
    storageBucket: 'veamordatingapp.firebasestorage.app',
    measurementId: 'G-CCTM5JZP03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA01c4d1uYsPGyspLYNJCcLR6C4eqOR2Cg',
    appId: '1:266111988879:android:136a9e87861a6e0a19acfa',
    messagingSenderId: '266111988879',
    projectId: 'veamordatingapp',
    storageBucket: 'veamordatingapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcRoZAzdg1kKDNX4m4B6LWQXBoJNJGSJE',
    appId: '1:266111988879:ios:fca61265d120580c19acfa',
    messagingSenderId: '266111988879',
    projectId: 'veamordatingapp',
    storageBucket: 'veamordatingapp.firebasestorage.app',
    androidClientId: '266111988879-ai2o925ems1kj8fr4nsm3agajadkstl3.apps.googleusercontent.com',
    iosClientId: '266111988879-d402sjkik8dolcpqv031f6elmji07nm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.veAmorApp',
  );

}